name: fraud_clustering
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  # Core packages from conda
  - pandas>=1.1,<2.0
  - numpy>=1.19,<2.0
  - scikit-learn>=0.24,<1.1
  - matplotlib>=3.3
  - seaborn>=0.11
  - plotly>=5.0
  # Specialized packages (conda-forge has better compatibility)
  - hdbscan>=0.8.27
  - umap-learn>=0.5.1
  # Additional dependencies via pip
  - pip
  - pip:
    - importlib-metadata>=4.0.0
    - typing-extensions>=4.0.0